# YOUR NAME OR TITLE OF YOUR SITE
name: Egee

# YOUR BRAND/PERSONAL TAGLINE
# tagline: Howdy, I'm Egee. I'm a passionate Tech Lover from Kanpur, apart from that I'm a Graphic Designer and an OpenSource enthusiast Inspired by Imagination.
tagline: Hiya, I'm Egee. I write code and make sound to help you sleep.

# YOUR/BRAND IMAGE URL
Image_URL: https://pbs.twimg.com/profile_images/1767654651300925440/NemAVxoe_400x400.jpg

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://images.unsplash.com/photo-1695683533112-21c8f8439ceb?q=80&w=1931&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D

# SOCIAL MEDIA
links:
  - Name: Egee's ASMR
    URL: https://www.youtube.com/
    Username: '@OpenEgee'
    Color: '#F20C0C'
    Icon-Class: fab fa-youtube

     # MASTODON.SOCIAL
  - Name: Mastodon
    URL: https://mastodon.social
    Username: '@egeexyz'
    Color: '#6364FE'
    Icon-Class: fa-brands fa-mastodon
    Text_Color: '#ffffff'

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: egee_irl
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

    # BLUESKY
  - Name: Bluesky
    URL: https://bsky.app/profile
    Username: 'egee.bsky.social'
    Color: '#6DB2FA'
    Icon-Class: fa-solid fa-square

    # YOUTUBE
  - Name: Egee's Hobbies
    URL: https://www.youtube.com/
    Username: '@egeexyz'
    Color: '#F20C0C'
    Icon-Class: fab fa-youtube

    # GITLAB
  - Name: Gitlab
    URL: http://gitlab.com
    Username: egee-irl
    Color: '#FC6D26'
    Icon-Class: fab fa-gitlab

    # STEAM
  - Name: Steam
    URL: https://steamcommunity.com/id
    Icon-Class: fa-brands fa-steam
    Username: 'egeexyz'
    Color: '#222B38'
    Text_Color: '#ffffff'

    # PATREON
  - Name: Patreon
    URL: 'https://www.patreon.com'
    Username: egeexyz
    Icon-Class: fa-brands fa-patreon
    Color: '#FC674D'
    Text_Color: '#ffffff'

    # DISCORD
  - Name: Discord
    URL: 'https://discord.com/servers'
    Username: egee-s-hobby-shop-183740337976508416
    Icon-Class: fab fa-discord
    Color: '#5865F2'
    Text_Color: '#ffffff'
  
    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: egeexyz
    Color: '#1A2B33'
    Icon-Class: fab fa-github

    # APPLE MUSIC
  - Name: Apple Music
    URL: https://music.apple.com/us/artist/egee
    Username: '1704222534'
    Icon-Class: fab fa-itunes
    Color: '#FB405A'
    Text_Color: '#ffffff'

    # TWITCH
  - Name: Twitch
    URL: 'https://twitch.tv'
    Username: egeexyz
    Icon-Class: fab fa-twitch
    Color: '#9147fe'
    Text_Color: '#ffffff'

    # SOUNDCLOUD
  - Name: SoundCloud
    URL: https://www.soundcloud.com
    Username: egeexyz
    Color: '#FE5000'
    Icon-Class: fab fa-soundcloud

    # SPOTIFY
  - Name: Spotify
    URL: http://open.spotify.com/artist
    Username: 7vaP2V4lYsKCLVbkFHPSKl
    Color: '#1DB954'
    Icon-Class: fab fa-spotify

    # REDDIT
  - Name: Reddit
    URL: http://reddit.com/u
    Username: egeeirl
    Color: '#FF4500'
    Icon-Class: fab fa-reddit-alien

    # MEDIUM
  - Name: Medium
    URL: 'https://medium.com'
    Username: '@egee_irl'
    Icon-Class: fab fa-medium-m
    Color: '#ffffff'
    Text_Color: '#000000'

    # DEVIANTART
  - Name: DeviantArt
    URL: https://www.deviantart.com
    Username: egee-irl
    Icon-Class: fab fa-deviantart
    Color: '#05CC46'
    Text_Color: '#ffffff'

     # FURAFFINITY
  - Name: FurAffinity
    URL: https://www.furaffinity.net/user
    Username: egeeirl
    Color: '#F1F3F4'
    Icon-Class: fa-solid fa-paw
    Text_Color: '#000000'

    # Hobby Linux
  - Name: Hobby Linux
    URL: https://github.com/Hobby-Linux
    Icon-Class: fa fa-linux
    Color: '#1DBFBF'
    Text_Color: '#ffffff'

    # UNSPLASH
  - Name: Unsplash
    URL: 'https://unsplash.com'
    Username: '@egeeirl'
    Icon-Class: fa-brands fa-unsplash
    Color: '#ffffff'
    Text_Color: '#000000'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'Yes'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
