name: Github Pages Build & Deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.5'
          bundler-cache: true
      - name: Upload static files as artifact
        run: jekyll build

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  # Deployment job
  # deploy:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       uses: actions/deploy-pages@v4
